INSERT INTO music_genre (genre)
VALUES ('Pop'),
    ('Rock'),
    ('Hip-Hop'),
    ('Country'),
    ('R&B'),
    ('Folk'),
    ('Jazz'),
    ('Classic'),
    ('Electronic'),
    ('Metal'),
    ('Latin'),
    ('Indie'),
    ('Soundtrack'),
    ('Ambient'),
    ('Dance'),
    ('Soul'),
    ('Reggae'),
    ('New Age');